/** Category of action recorded in a guild's audit log. */
export enum GuildAuditAction {
  GuildRegistered = 'GuildRegistered',
  SettingsUpdated = 'SettingsUpdated',
  MemberJoined = 'MemberJoined',
  MemberLeft = 'MemberLeft',
  MemberExcluded = 'MemberExcluded',
  MemberRankUpdated = 'MemberRankUpdated',
  OfficerThresholdUpdated = 'OfficerThresholdUpdated',
  AvailabilityExceptionDeclared = 'AvailabilityExceptionDeclared',
  AvailabilityExceptionDeleted = 'AvailabilityExceptionDeleted',
  RecurringAvailabilityPatternCreated = 'RecurringAvailabilityPatternCreated',
  RecurringAvailabilityPatternUpdated = 'RecurringAvailabilityPatternUpdated',
  RecurringAvailabilityPatternStopped = 'RecurringAvailabilityPatternStopped',
  NotificationSettingsUpdated = 'NotificationSettingsUpdated',
  BranchActivated = 'BranchActivated',
  BranchDeactivated = 'BranchDeactivated',
  BranchRosterSettingsUpdated = 'BranchRosterSettingsUpdated',
  NotificationSettingsReset = 'NotificationSettingsReset',
  RaidSeriesCreated = 'RaidSeriesCreated',
  RaidSeriesUpdated = 'RaidSeriesUpdated',
  RaidSeriesDeactivated = 'RaidSeriesDeactivated',
  RaidEventCreated = 'RaidEventCreated',
  RaidEventUpdated = 'RaidEventUpdated',
  RaidEventDeleted = 'RaidEventDeleted',
  RaidEventPublished = 'RaidEventPublished',
  BranchRegionUpdated = 'BranchRegionUpdated',
  SlotAssigned = 'SlotAssigned',
  SlotUnassigned = 'SlotUnassigned',
  SlotsSwapped = 'SlotsSwapped',
  SlotAssignmentSpecChanged = 'SlotAssignmentSpecChanged',
}
