sonar.projectKey=Bhahlou_RaidOps.Front
sonar.organization=bhahlou

sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/test-setup.ts,**/environments/**,**/*.model.ts
sonar.coverage.exclusions=**/*.routes.ts,**/main.ts,**/app.config.ts
sonar.cpd.exclusions=**/changelog-entries.data.ts
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.typescript.tsconfigPath=tsconfig.json
